# 网站基本信息
title: "Simple Jekyll Blog"
email: your-email@example.com
description: >-
  一个简洁的Jekyll博客模板，适合学术研究者和技术博客使用。
  支持数学公式、代码高亮、响应式设计等功能。

baseurl: ""
url: "https://your-username.github.io"

# 作者信息
author:
  name: "Your Name"
  title: "Your Title"
  email: "your-email@example.com"
  bio: "简短的个人介绍"

# 构建设置
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    block:
      line_numbers: true

highlighter: rouge
permalink: pretty

# 分页设置
paginate: 5
paginate_path: "/page:num/"

# MathJax配置
mathjax:
  enable: true
  combo: "tex-mml-chtml"
  tags: "ams"

# 性能优化配置
incremental: true
future: false
show_drafts: false
unpublished: false
lsi: false
safe: true

# HTML压缩
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [development]
  blanklines: false
  profile: false
  startings: [html, head, body]

# 限制相关文章计算以提高速度
lsi: false
related_posts_limit: 5
limit_posts: 50

# 插件
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# 功能开关
features:
  search: true
  comments: false
  analytics: false
  dark_mode: true
  mathjax: true

# 导航菜单
navigation:
  - title: "首页"
    url: /
  - title: "关于"
    url: /about/
  - title: "文章"
    url: /posts/
  - title: "标签"
    url: /tags/

# 社交链接
social:
  github: your-github-username
  twitter: your-twitter-handle
  linkedin: your-linkedin-profile
  email: your-email@example.com

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/

# 包含文件
include:
  - _pages
