name: Build and Deploy with Optimizations
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install Node.js dependencies
      run: |
        npm install -g html-minifier-terser clean-css-cli uglify-js imagemin-cli imagemin-webp imagemin-mozjpeg imagemin-pngquant
    - name: Install Ruby dependencies
      run: bundle install
        
    - name: Optimize Images
      run: |
        if [ -d "./pictures" ]; then
          echo "优化图片..."
          find ./pictures -name "*.jpg" -o -name "*.jpeg" | xargs -r -I {} imagemin {} --out-dir=./pictures --plugin=mozjpeg || echo "JPEG优化跳过"
          find ./pictures -name "*.png" | xargs -r -I {} imagemin {} --out-dir=./pictures --plugin=pngquant || echo "PNG优化跳过"
          find ./pictures -name "*.jpg" -o -name "*.jpeg" -o -name "*.png" | xargs -r -I {} imagemin {} --out-dir=./pictures --plugin=webp || echo "WebP转换跳过"
        else
          echo "pictures目录不存在，跳过图片优化"
        fi
        
    - name: Build Site
      run: |
        bundle exec jekyll build --profile
        
    - name: Minify HTML, CSS, JS
      run: |
        echo "压缩HTML文件..."
        find ./_site -name "*.html" | xargs -r -I {} html-minifier-terser {} --remove-comments --collapse-whitespace --file-ext html || echo "HTML压缩跳过"
        
        echo "压缩CSS文件..."
        find ./_site -name "*.css" | xargs -r -I {} cleancss {} -o {} || echo "CSS压缩跳过"
        
        echo "压缩JS文件..."
        find ./_site -name "*.js" | xargs -r -I {} uglifyjs {} -c -m -o {} || echo "JS压缩跳过"
        
    - name: Generate sitemap
      run: |
        bundle exec jekyll build --trace
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
