name: Build and Deploy with Optimizations
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
        
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install Dependencies
      run: |
        bundle install
        npm install -g imagemin-cli imagemin-webp imagemin-mozjpeg imagemin-pngquant
        
    - name: Optimize Images
      run: |
        find ./pictures -name "*.jpg" -o -name "*.jpeg" | xargs -I {} imagemin {} --out-dir=./pictures --plugin=mozjpeg
        find ./pictures -name "*.png" | xargs -I {} imagemin {} --out-dir=./pictures --plugin=pngquant
        find ./pictures -name "*.jpg" -o -name "*.jpeg" -o -name "*.png" | xargs -I {} imagemin {} --out-dir=./pictures --plugin=webp
        
    - name: Build Site
      run: |
        bundle exec jekyll build --profile
        
    - name: Minify HTML, CSS, JS
      run: |
        find ./_site -name "*.html" | xargs -I {} htmlmin {} --remove-comments --collapse-whitespace --output {}
        find ./_site -name "*.css" | xargs -I {} cleancss {} -o {}
        find ./_site -name "*.js" | xargs -I {} uglifyjs {} -c -m -o {}
        
    - name: Generate sitemap
      run: |
        bundle exec jekyll build --trace
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
