name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 或 master，取决于你的默认分支

permissions:
  contents: write  # 必须！

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - run: bundle install
      - run: bundle exec jekyll build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
