name: 自动更新 Blog Index
on:
  schedule:
    - cron: '0 * * * *' # 每小时运行一次
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: 生成 blog/index.json
        run: |
          node genBlogIndex.js
      - name: 提交并推送更改
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add blog/index.json
          git diff --cached --quiet || git commit -m 'auto: update blog index'
          git push
